---
## tasks file for java

########## Delete Java ################
 - name: Delete Java
   block:
   - name: Check Java Installation Directory
     stat:
       path: "{{ JAVA_INSTALL_DIR }}"
     register: java_result

   - debug:
       msg: "Java is installed. Deleting java..."
     when: java_result.stat.exists == true

   - debug:
       msg: "Java is not installed. Skipping..."
     when: java_result.stat.exists == false

   - name: Delete Java
     file: 
       path: "{{ JAVA_INSTALL_DIR }}"
       state: absent
   
   - debug:
       msg: "Java deleted successfully"
     when: java_result.stat.exists == true
   rescue: 
   - fail:
       msg: "Error on {{ JAVA_INSTALL_DIR }} deletion"
   tags:
     - never
     - delete-java
     - install-all

 - name: Java Installation
   block:
   - name: Check if Java is Installed
     stat:
       path: "{{ JAVA_INSTALL_DIR }}"
     register: java_result

   - debug:
       msg: "Java is installed. Skipping..."
     when: java_result.stat.exists == true

   - debug:
       msg: "Java is not installed. Installing..."
     when: java_result.stat.exists == false

   - name: Create Java Install directory
     file:
       path: "{{ JAVA_INSTALL_DIR }}"
       state: directory

   - name: Download and Extract JDK tar file
     unarchive:
       src: "{{ JAVA_URL }}"
       dest: "{{ JAVA_INSTALL_DIR }}"
       remote_src: true
       extra_opts: [--strip-components=1]

   - name: Set JAVA_HOME
     lineinfile:
       dest: "~/.bashrc"
       regexp: "'^JAVA_HOME'>"
       line: "export JAVA_HOME={{ JAVA_INSTALL_DIR }}"

   - name: Set Java PATH
     lineinfile:
       dest: "~/.bashrc"
       regexp: "'^JAVA_HOME'>"
       line: "export PATH=$M2:$PATH:{{ JAVA_INSTALL_DIR }}/bin"

   - name: Run Source Bashrc
     shell: "source ~/.bashrc"

   - debug: 
       msg: "Java Installed Successfully"
     when: java_result.stat.exists == false

   rescue:
   - fail:  
       msg: "Error on {{ JAVA_INSTALL_DIR }} installation"

   tags:
     - never
     - install-java
     - install-all


