---
# tasks file for ansible_role

  - name: Create Install directories for Tomcat and Java
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ SETUP_DIR }}"
      - "{{ TOMCAT_HOME_DIR }}"
      - "{{ JAVA_HOME_DIR }}"

  - name: Download tars into  Java and Tomcat directories
    get_url:
      url: "{{ item }}"
      dest: "{{ SETUP_DIR }}"
    with_items:
      - "{{ JAVA_URL }}"
      - "{{ TOMCAT_URL }}"

  - name: Extract JDK tar file
    unarchive:
      src: "{{ JAVA_ZIP }}"
      dest: "{{ JAVA_HOME_DIR }}"
      remote_src: true
      extra_opts: [--strip-components=1]

  - name: Extract Tomcat tar file
    unarchive:
      src: "{{ TOMCAT_ZIP }}"
      dest: "{{ TOMCAT_HOME_DIR }}"
      remote_src: true
      extra_opts: [--strip-components=1]

  - name: Set JAVA_HOME
    lineinfile:
      dest: "~/.bashrc"
      regexp: "'^JAVA_HOME'>"
      line: "export JAVA_HOME={{ JAVA_HOME_DIR }}"

  - name: Set Java PATH
    lineinfile:
      dest: "~/.bashrc"
      regexp: "'^JAVA_HOME'>"
      line: "export PATH=$M2:$PATH:{{ JAVA_HOME_DIR }}/bin"

  - name: Run Source Bashrc
    shell: "source ~/.bashrc"

  - name: Deploy tar file
    copy:
      src: "{{ DEPLOY_WAR }}"
      dest: "{{ TOMCAT_HOME_DIR }}/webapps"

  - name: Start Webserver
    shell: "nohup ./startup.sh run >> ../logs/appserver.log &"
    args:
      chdir: "{{ TOMCAT_HOME_DIR }}/bin"
